DEBUG = True
SOCIAL_AUTH_FACEBOOK_KEY = '589010857788027'
SOCIAL_AUTH_FACEBOOK_SECRET =  'aaf0f16f8d2bf3fc3372c9ca748b4d1c'
SOCIAL_AUTH_FACEBOOK_APP_NAMESPACE = ''
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
# SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {'locale': 'ru_RU'}

SOCIAL_AUTH_TWITTER_KEY = ''
SOCIAL_AUTH_TWITTER_SECRET = ''

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '972886593405-l15vq2p4obk54pfh9m6ik7vdachu1cqg.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 't9OY3KaTYw4reBQML3ha_v3v'

SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = [
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/userinfo.profile'
]
